#!/bin/sh
#

BOOKTITLE="Linux Fundamentals"
TEACHER=""

###########################
## OBSOLETE chapter definitions
###########################
# . $BOOKSDIR/chapters
	
##################
# define book
##################

# define book as collection of minibooks in certain order

add_mod minibook minibook_introduction
add_mod minibook minibook_first_steps
add_mod minibook minibook_shell
add_mod minibook minibook_pipes_and_commands
add_mod minibook minibook_vi
add_mod minibook minibook_scripts
add_mod minibook minibook_users
add_mod minibook minibook_files
#add_mod chapter intro_processes

#add_mod appendix keys
#add_mod appendix hardware

# license
# (automatic at end of pdf file ?)
add_mod appendix license
