#!/bin/sh
#

BOOKTITLE="Linux Training"
TEACHER=""

###########################
## chapter definitions
###########################

. $BOOKSDIR/chapters
	
##################
# define book
##################

# define book as chapters in certain order

# fundamentals
add_mod chapter intro_unix
add_mod chapter getting_help
add_mod chapter intro_directories
add_mod chapter intro_files
add_mod chapter intro_file_contents
add_mod chapter file_system_tree

add_mod chapter shell_introduction
add_mod chapter shell_control_operators
add_mod chapter shell_variables
add_mod chapter shell_arguments
add_mod chapter shell_history
add_mod chapter shell_globbing
add_mod chapter shell_io

add_mod chapter pipes_filters
add_mod chapter basic_tools
add_mod chapter intro_vi
add_mod chapter intro_scripts

add_mod chapter intro_users
add_mod chapter intro_groups
add_mod chapter file_permissions
add_mod chapter advanced_permissions
add_mod chapter acls
add_mod chapter links
add_mod chapter intro_processes

add_mod appendix keys
add_mod appendix hardware

# sysadmin
add_mod chapter processes
add_mod chapter disk_management
add_mod chapter lvm
add_mod chapter bootloader
add_mod chapter init_system
add_mod chapter kernel
add_mod chapter network_sniffing
add_mod chapter network
add_mod chapter scheduling
add_mod chapter logging
add_mod chapter libraries
add_mod chapter memory 
add_mod chapter installing_linux
add_mod chapter package_management
add_mod chapter backup
add_mod chapter monitoring
add_mod appendix quotas
add_mod appendix vnc
# add_mod appendix bootfloppy
# advanced servers
add_mod chapter apache
add_mod chapter squid
add_mod chapter mysql
add_mod chapter bind
add_mod chapter router
add_mod chapter iptables
add_mod chapter cloning
add_mod chapter selinux
# samba
add_mod chapter samba_introduction
add_mod chapter samba_getting_started
add_mod chapter samba_read_only_file_server
add_mod chapter samba_writable_file_server
add_mod chapter samba_first_user_account
add_mod chapter samba_authentication
add_mod chapter samba_securing_shares
add_mod chapter samba_domain_member
add_mod chapter samba_domain_controller
add_mod chapter samba4

# License
add_mod appendix gnufdl
