#!/bin/sh
#

BOOKTITLE="Linux Training"
TEACHER=""

###########################
## chapter definitions
###########################

. $BOOKSDIR/chapters
	
##################
# define book
##################

# define book as chapters in certain order

# fundamentals
add_chapt intro_unix
add_chapt getting_help
add_chapt intro_directories
add_chapt intro_files
add_chapt intro_file_contents
add_chapt file_system_tree

add_chapt shell_introduction
add_chapt shell_control_operators
add_chapt shell_variables
add_chapt shell_arguments
add_chapt shell_history
add_chapt shell_globbing
add_chapt shell_io

add_chapt pipes_filters
add_chapt basic_tools
add_chapt intro_vi
add_chapt intro_scripts

add_chapt intro_users
add_chapt intro_groups
add_chapt file_permissions
add_chapt advanced_permissions
add_chapt acls
add_chapt links
add_chapt intro_processes

add_appen keys
add_appen hardware

# sysadmin
add_chapt processes
add_chapt disk_management
add_chapt lvm
add_chapt bootloader
add_chapt init_system
add_chapt kernel
add_chapt network_sniffing
add_chapt network
add_chapt scheduling
add_chapt logging
add_chapt libraries
add_chapt memory 
add_chapt installing_linux
add_chapt package_management
add_chapt backup
add_chapt monitoring
add_appen quotas
add_appen vnc
# add_appen bootfloppy
# advanced servers
add_chapt apache
add_chapt squid
add_chapt mysql
add_chapt bind
add_chapt router
add_chapt iptables
add_chapt cloning
add_chapt selinux
# samba
add_chapt samba_introduction
add_chapt samba_getting_started
add_chapt samba_read_only_file_server
add_chapt samba_writable_file_server
add_chapt samba_first_user_account
add_chapt samba_authentication
add_chapt samba_securing_shares
add_chapt samba_domain_member
add_chapt samba_domain_controller
add_chapt samba4

# License
add_appen gnufdl
