#!/bin/sh
#

BOOKTITLE="backup management"

##################
# define minibook
##################

# define book as directories in certain order
add_mod chapter backup
#add_mod chapter backup_examples #local copy only for one client
