#!/bin/sh
#

BOOKTITLE="Linux System Administration"
TEACHER=""
# if set this overrules the system wide version:
MAJOR=0
MINOR=99


###########################
## chapter definitions
###########################

. $BOOKSDIR/chapters
	
##################
# define book
##################

# define book as chapters in certain order

# fundamentals parts in sysadmin course
# add_mod chapter intro_users
# add_mod chapter intro_groups
# add_mod chapter file_permissions
# add_mod chapter links
# add_mod chapter processes

# sysadmin
add_mod chapter processes
add_mod chapter disk_management
add_mod chapter lvm
add_mod chapter bootloader
add_mod chapter init_system
add_mod chapter kernel
add_mod chapter network_sniffing
add_mod chapter network
add_mod chapter scheduling
add_mod chapter logging
add_mod chapter libraries
add_mod chapter memory 
add_mod chapter installing_linux
add_mod chapter package_management
add_mod chapter backup
add_mod chapter monitoring
add_mod appendix quotas
add_mod appendix vnc
# add_mod appendix bootfloppy

# license
add_mod appendix gnufdl
