#!/bin/sh
#

BOOKTITLE="process management"

##################
# define minibook
##################

# define book as directories in certain order
add_mod chapter processes_intro
add_mod chapter processes_priority
add_mod chapter processes_jobs
