#!/bin/sh
#

BOOKTITLE="the shell"

##################
# define minibook
##################

# define book as directories in certain order

add_chapt shell_shell_introduction
add_chapt shell_shell_control_operators
add_chapt shell_shell_variables
add_chapt shell_shell_arguments
add_chapt shell_shell_history
add_chapt shell_shell_globbing
add_chapt shell_shell_io

# license hardcoden op het einde van een .pdf ?
# add_appen gnufdl
