#!/bin/sh
#

BOOKTITLE="shell expansion"

##################
# define minibook
##################

# define book as directories in certain order

add_mod chapter shell_arguments
add_mod chapter shell_control_operators
add_mod chapter shell_variables
add_mod chapter shell_in_shell
add_mod chapter shell_history
add_mod chapter shell_globbing

# license hardcoden op het einde van een .pdf ?
# add_mod appendix gnufdl
