#!/bin/sh
#

BOOKTITLE="Netwerken"

##################
# define minibook
##################

# define book as directories in certain order

add_mod chapter NL_geschiedenis_internet
add_mod chapter NL_netwerken_terminologie
add_mod chapter NL_netwerken_lagen
add_mod chapter NL_netwerken_sniffer
add_mod chapter NL_netwerken_onze_data_op_reis
add_mod chapter NL_netwerken_enkele_protocols
add_mod chapter NL_talstelsels
add_mod chapter NL_netwerken_ipadressen
add_mod chapter NL_netwerken_ipadressen_binair

add_mod chapter license
