#!/bin/sh
#

BOOKTITLE="network management"

##################
# define minibook
##################

# define book as directories in certain order
add_mod chapter general_networking
add_mod chapter general_tcpip
add_mod chapter network_sniffing
add_mod chapter ipv4_addressing
add_mod chapter classful_subnets # still has parts in Dutch
add_mod chapter classless_subnets # still has parts in Dutch
add_mod chapter network
