#!/bin/sh
#

BOOKTITLE="disk management"

##################
# define minibook
##################

# define book as directories in certain order
add_mod chapter disk_devices
add_mod chapter disk_partitions
add_mod chapter disk_filesystems
add_mod chapter disk_mounting
add_mod chapter uuid
add_mod chapter storage_raid
add_mod chapter lvm
add_mod chapter disk_iscsi
