#!/bin/sh
#

BOOKTITLE="local user management"

##################
# define minibook
##################

# define book as directories in certain order

add_mod chapter intro_users
add_mod chapter intro_groups
# possibly separate passwords chapter ?
# separate su - sudo chapter ??
