#!/bin/sh
#

BOOKTITLE="introduction to Linux"

##################
# define minibook
##################

# define book as directories in certain order

add_mod chapter linux_history
add_mod chapter linux_distributions
add_mod chapter licensing
add_mod chapter virtualbox

#add_mod appendix certifications # appendices only in books, not in miniboooks...
