#!/bin/sh
#

BOOKTITLE="Samba"
TEACHER=""

###########################
## chapter definitions
###########################

. $BOOKSDIR/chapters
	
##################
# define book
##################

# define book as chapters in certain order

add_mod chapter samba_introduction
add_mod chapter samba_getting_started
add_mod chapter samba_read_only_file_server
add_mod chapter samba_writable_file_server
add_mod chapter samba_first_user_account
add_mod chapter samba_authentication
add_mod chapter samba_securing_shares
add_mod chapter samba_domain_member
add_mod chapter samba_domain_controller
add_mod chapter samba4

# License
add_mod appendix gnufdl
