#!/bin/sh
#

BOOKTITLE="pipes and commands"

##################
# define minibook
##################

# define book as directories in certain order

add_mod chapter redirection_and_pipes
add_mod chapter filters
add_mod chapter basic_tools
add_mod chapter regular_expressions

# license hardcoden op het einde van een .pdf ?
# add_mod appendix gnufdl
