#!/bin/sh
#

BOOKTITLE="Linux Servers"
TEACHER=""
# if set this overrules the system wide version:
MAJOR=0
MINOR=5

##################
# define book
##################

# define book as chapters in certain order

# advanced servers
add_mod chapter apache
add_mod chapter squid
add_mod chapter mysql
add_mod chapter bind
add_mod chapter router
add_mod chapter iptables
add_mod chapter cloning
add_mod chapter selinux
add_mod chapter samba

# license
add_mod appendix license
